"""
Django settings for Qshop project.

Generated by 'django-admin startproject' using Django 2.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '(*c$w(ye4e3&yxch4@b(yg95!r6)ur$rkby6364_pjar2j$=%%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Seller',
    'Market',
    'Market.templatetags'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Qshop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Qshop.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

#数据库配置
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': "Qshop",
        "HOST":"localhost",
        "USER":"root",
        "PASSWORD":"123456",
        "PORT":3306
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/ShangHai'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS=(os.path.join(BASE_DIR,"static"),)

MEDIA_URL="/media/"
MEDIA_ROOT=os.path.join(BASE_DIR,"static")
# STATIC_ROOT=os.path.join(BASE_DIR,"static") #收集静态文件配置


##实现支付宝demo ,所有实现接口的都放在sdk中
#固定格式，5个横杠
#公钥
alipay_public_key_string="""-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqTe9BH7cHNINmOSQCxzcI4HUgEeKLuBoI2tObZVM53+JsFm1RtAvV590pBCS8a1kCDiMFVJoJ1ut1N+YvTuLSi20u2+iAvCvnT8k8Mr4AT++GtSb5oKD8Tez/HHrw9yURc4ajtYgiJu+UWgXx1J8rVWLfDmqqUaURunO93IQ7lulTOpTghMtYedyxXXSPRzg3vt20aUqE2hxTxTiIvmpxeq38MGc1QgzfBEMNaALsN7JxuK7jC92npzxo60AvyNxEvivy8XyuFGIc77qBNgVOpOD6msIWoHkH8WFPPkGbjEhQIVhNJ8eWHoKXvAPGThQs9sTJLw84r34745CinLJwQIDAQAB
-----END PUBLIC KEY-----"""
#私钥
app_private_key_string="""-----BEGIN RSA PRIVATE KEY-----
MIIEpAIBAAKCAQEAqTe9BH7cHNINmOSQCxzcI4HUgEeKLuBoI2tObZVM53+JsFm1RtAvV590pBCS8a1kCDiMFVJoJ1ut1N+YvTuLSi20u2+iAvCvnT8k8Mr4AT++GtSb5oKD8Tez/HHrw9yURc4ajtYgiJu+UWgXx1J8rVWLfDmqqUaURunO93IQ7lulTOpTghMtYedyxXXSPRzg3vt20aUqE2hxTxTiIvmpxeq38MGc1QgzfBEMNaALsN7JxuK7jC92npzxo60AvyNxEvivy8XyuFGIc77qBNgVOpOD6msIWoHkH8WFPPkGbjEhQIVhNJ8eWHoKXvAPGThQs9sTJLw84r34745CinLJwQIDAQABAoIBAFcpQ642HfCmbaSMTnm64tVTQX7V2qJsqpdb5Wjil1tCwUxZ2NrhzxDmLHF5rAbaVgU6A0XUTZvASFi213jZW9TYmBhX1u6GxR5M8R0qnvYdvDEbxDXGkmnEVGw6zcL0MleGYv2h494Zwr0xzdW4ckniH1fcaECK/0NLmXSxh3EOYvCv8yuEIr4oAnCvYaMvE/nB5O9swx/h4FbxGJSR7DBRaglNEa6OhAiSFBgWLUtKD+Kqh8Kc2A4Oz6TQHwWiwIvPbfOCPos86fiPDbOphpgD/aAxeUIJjRk2rFOal6EclYynZt/hcCZ0sDc8FDs3ofdPuyx+m6NibQc2cJM8JoUCgYEA20RRo8vQH7tKK3qtpX5W5HYvVLqlqvPSRT1dXLfAAMDXVhmc++lItlwIxD4DECo3fzpTZslV85CoFjNDD3YqEMjUDVbSUFzTGFSPgrRzmgDIfgokNNN03R+/cCrd1Kf8q1VT4xEvk1KilG2PszPmyf9dmyyGtmp5xeJ4/jOfftMCgYEAxZD3PWxjPHhHxryueqPJFDFct5FoTEU3a7o4sFoqdum/VJBL0iI/+yQv9Bs9LQVMDxxbcNeYBbp+BEO5s1vvU5NBw9sEnwB07THbGDYmx3WvGlHyWVgWR0APv1Ap3fCM2aYlGNttTE6hYHtZtGENwAPLU24VM/HqJgKRklD7AJsCgYAEqfVamJE6u48eUaOz63YJsgHbuYSgmEMWufFscXQiD/gEmtLeAN5NErQVCISkKWG40RLJEutDHQaWQkzg3VCTvtHT3s7marMKx3GuBAyZb/7Tv395qC3KLkyyJBdH2LLlKhF4uPrcFVvj8FioJSh5j3b8P/w1kRo5/VE5hvuThQKBgQCTv1TWj58rEryCyIonVyNCQaQX99sq5ryKiMpqQBPvt+EJKZw6OrjkZOyjvlciuwplZoyPt/uNlSk2oTtYAdHaC48sHDe5fQr0c8tosN6RXdYkddIqtLB8elEMfrPAsWt0PUcS7s4vOcJ/t9+fANHanjvJWdLrdOfpoxQgewUrLwKBgQDKN7KuLAgtaBt7LCFKI5zykocTElQhbZuEjPcYsMkH0gy44J4IRb7rkmUbF7EVAUqUzS6GiVuEZxbyzLXgHcpAMrswuYTKq5X/FBlLcPKSV9GwKI7eCXGDEsCuQmHIfjUDyva+Ii/3ROdUQ5c3KRmCYf8KVsGKlR1fci+bd5XH4Q==
-----END RSA PRIVATE KEY-----"""

#1.导包 #在创建文件是不能使用alipay
from alipay import AliPay
#2.创建一个实例对象
alipay=AliPay(
    appid="2016101800717516",#商户的appid-在沙箱应用
    app_notify_url=None,
    app_private_key_string=app_private_key_string,
    alipay_public_key_string=alipay_public_key_string,
    sign_type="RSA2",
    debug=False
)


