# Generated by Django 2.2.1 on 2020-02-27 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0002_auto_20200227_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payorder',
            name='order_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.LoginUser', to_field='email', verbose_name='买家'),
        ),
    ]
