# Generated by Django 2.2.1 on 2020-02-27 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0003_auto_20200227_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.LoginUser', to_field='email', verbose_name='卖家邮箱'),
        ),
    ]
