# Generated by Django 2.2.1 on 2020-03-06 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0006_auto_20200306_2100'),
        ('Market', '0006_auto_20200302_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addinfo', models.CharField(max_length=60, verbose_name='详细地址')),
                ('yinfo', models.CharField(max_length=10, verbose_name='邮编')),
                ('tel', models.CharField(max_length=11, verbose_name='电话号码')),
                ('ischecked', models.IntegerField(choices=[(1, '是'), (0, '否')], verbose_name='是否默认')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.LoginUser', to_field='email', verbose_name='买家')),
            ],
            options={
                'verbose_name_plural': '详细地址表',
                'db_table': 'Useraddress',
            },
        ),
    ]
