# Generated by Django 2.2.1 on 2020-03-06 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0007_useraddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='uname',
            field=models.CharField(default='duhuihuang', max_length=32, verbose_name='姓名'),
            preserve_default=False,
        ),
    ]
