# Generated by Django 2.2.1 on 2020-02-26 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='姓名')),
                ('email', models.EmailField(max_length=20, unique=True, verbose_name='邮箱')),
                ('password', models.CharField(max_length=50, verbose_name='密码')),
                ('phone_num', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='出生年月')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='年龄')),
                ('picture', models.ImageField(default='img/tx.jpg', upload_to='img', verbose_name='个人头像')),
                ('gender', models.IntegerField(choices=[(0, '女'), (1, '男')], default=0, verbose_name='性别')),
                ('address', models.TextField(blank=True, null=True, verbose_name='地址')),
                ('createtime', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('user_status', models.IntegerField(choices=[(0, '买家'), (1, '卖家')], default=0, verbose_name='用户类型')),
                ('isDelete', models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否删除')),
            ],
            options={
                'verbose_name_plural': '用户表',
                'db_table': 'loginuser',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sup_name', models.CharField(max_length=32, verbose_name='供应商名称')),
                ('sup_country', models.CharField(blank=True, max_length=32, null=True, verbose_name='供应商/国籍')),
                ('sup_province', models.CharField(blank=True, max_length=32, null=True, verbose_name='省/州')),
                ('sup_city', models.CharField(blank=True, max_length=32, null=True, verbose_name='市')),
                ('sup_area', models.CharField(blank=True, max_length=32, null=True, verbose_name='区县')),
                ('sup_address', models.TextField(blank=True, max_length=32, null=True, verbose_name='具体地址')),
                ('sup_phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('sup_tel', models.CharField(blank=True, max_length=15, null=True, verbose_name='座机电话')),
                ('sup_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱')),
                ('sup_sex', models.IntegerField(choices=[(0, '女'), (1, '男')], default=0, verbose_name='性别')),
                ('sup_user', models.CharField(max_length=20, verbose_name='联系人')),
                ('sup_status', models.IntegerField(choices=[(0, '合作'), (1, '终止')], default=0, verbose_name='是否合作')),
            ],
            options={
                'verbose_name_plural': '供应商表',
                'db_table': 'supplier',
            },
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typename', models.CharField(max_length=32, verbose_name='类型名称')),
                ('typeimg', models.ImageField(default='images/goods.jpg', upload_to='images', verbose_name='类型图片')),
            ],
            options={
                'verbose_name_plural': '商品类型表',
                'db_table': 'types',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Goods_num', models.CharField(max_length=13, verbose_name='商品编号')),
                ('Goods_name', models.CharField(max_length=32, verbose_name='商品名称')),
                ('Goods_price', models.FloatField(verbose_name='销售单价')),
                ('Goods_count', models.IntegerField(verbose_name='商品数量')),
                ('Goods_location', models.CharField(blank=True, max_length=32, null=True, verbose_name='商品产地')),
                ('Goods_safe_date', models.IntegerField(blank=True, null=True, verbose_name='保质期(天)')),
                ('Goods_pro_date', models.DateTimeField(auto_now=True, verbose_name='生产日期')),
                ('Goods_status', models.IntegerField(choices=[(0, '在售'), (1, '停售')], default=0, verbose_name='商品状态')),
                ('Goods_inprice', models.FloatField(verbose_name='成本价')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.Supplier')),
                ('types', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.Types')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.LoginUser', to_field='email')),
            ],
            options={
                'verbose_name_plural': '商品表',
                'db_table': 'goods',
            },
        ),
    ]
