# Generated by Django 2.2.1 on 2020-02-26 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='Goods_img',
            field=models.ImageField(default='img/tx.jpg', upload_to='img', verbose_name='商品图片'),
        ),
    ]
