# Generated by Django 2.2.1 on 2020-02-26 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0002_goods_goods_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='Goods_pro_date',
            field=models.DateField(auto_now=True, verbose_name='生产日期'),
        ),
    ]
