# Generated by Django 2.2.1 on 2020-02-27 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0004_auto_20200227_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='Goods_des',
            field=models.TextField(blank=True, null=True, verbose_name='商品描述'),
        ),
        migrations.AddField(
            model_name='goods',
            name='Goods_info',
            field=models.TextField(blank=True, null=True, verbose_name='详细信息'),
        ),
    ]
