# Generated by Django 2.2.1 on 2020-02-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='登录名')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('isDelete', models.IntegerField(default=0, verbose_name='是否删除')),
            ],
            options={
                'verbose_name_plural': '用户表',
                'db_table': 'users',
            },
        ),
    ]
