# Generated by Django 2.2.1 on 2020-02-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='createtime',
            field=models.DateTimeField(auto_now=True, verbose_name='创建时间'),
        ),
    ]
